/**
 * 
 */
package model;

/**
 * @author Relic
 *
 */
public enum AnimationKind {
	NEWSMOKE, NEWFIREONSMOKE, EXPLOSION, 
	NEIGHBORSMOKE, 
	DANGERWITHFIRE, 
	FIREONSEAT, NEWSEAT, 
	FALSEALARM, PERSONFOUND, 
	EXTENDFINDFALSEALAARM, EXTENDFINDDEADPERSON,
	KILLEDPERSON,SAVEDPERSON, 
	KNOCKEDFIREFIGHTER;

}
