/**
 * 
 */
package model;

/**
 * @author Relic
 *
 */
public enum SpecialistType {
	
	DUMMY, RETTUNGSSANITAETER, EINSATZLEITER, SPEZIALIST_MIT_WAERMEBILDKAMERA, LOESCHSCHAUMSPEZIALIST, GEFAHRSTOFFSPEZIALIST, ALLESKOENNER, RETTUNGSSPEZIALIST, FAHRZEUGMASCHINIST;

}
